// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKv7TQoq6ojK7McK0j3gk0zQBMr7Hga78',
    appId: '1:1013239437397:web:d582bf52fc8941dec79cdc',
    messagingSenderId: '1013239437397',
    projectId: 'speakup-69ed7',
    authDomain: 'speakup-69ed7.firebaseapp.com',
    storageBucket: 'speakup-69ed7.firebasestorage.app',
    measurementId: 'G-27F6LP4SSC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNAy-8hFhqZWF0rprZh2Dc5NR3xikoB9I',
    appId: '1:1013239437397:android:00e05e30bc8ec500c79cdc',
    messagingSenderId: '1013239437397',
    projectId: 'speakup-69ed7',
    storageBucket: 'speakup-69ed7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAberfxXtgkxCWRUl9gg-8swkxN-5DshHg',
    appId: '1:1013239437397:ios:5d7d48ee5f29abf3c79cdc',
    messagingSenderId: '1013239437397',
    projectId: 'speakup-69ed7',
    storageBucket: 'speakup-69ed7.firebasestorage.app',
    iosClientId: '1013239437397-na5cqge3ksbpjrdoimhj1m4bv4laeqtu.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartAacSpeechLearning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAberfxXtgkxCWRUl9gg-8swkxN-5DshHg',
    appId: '1:1013239437397:ios:5d7d48ee5f29abf3c79cdc',
    messagingSenderId: '1013239437397',
    projectId: 'speakup-69ed7',
    storageBucket: 'speakup-69ed7.firebasestorage.app',
    iosClientId: '1013239437397-na5cqge3ksbpjrdoimhj1m4bv4laeqtu.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartAacSpeechLearning',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKv7TQoq6ojK7McK0j3gk0zQBMr7Hga78',
    appId: '1:1013239437397:web:2e68544dac0ee614c79cdc',
    messagingSenderId: '1013239437397',
    projectId: 'speakup-69ed7',
    authDomain: 'speakup-69ed7.firebaseapp.com',
    storageBucket: 'speakup-69ed7.firebasestorage.app',
    measurementId: 'G-ZM10LC61VM',
  );
}
